package com.roberthevesi.cryptoshred_health.service;

import com.roberthevesi.cryptoshred_health.controller.AdminController;
import com.roberthevesi.cryptoshred_health.dto.AdminUserRequest;
import com.roberthevesi.cryptoshred_health.dto.AdminUserResponse;
import com.roberthevesi.cryptoshred_health.model.Role;
import com.roberthevesi.cryptoshred_health.model.User;
import com.roberthevesi.cryptoshred_health.repository.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

class AdminStaffProvisioningTest {

    private UserRepository userRepository;
    private PasswordEncoder passwordEncoder;
    private AdminController adminController;

    @BeforeEach
    void setUp() {
        userRepository = mock(UserRepository.class);
        passwordEncoder = mock(PasswordEncoder.class);
        when(passwordEncoder.encode(anyString())).thenAnswer(invocation -> "encoded_" + invocation.getArgument(0));

        adminController = new AdminController(userRepository, passwordEncoder);
    }

    @Test
    @DisplayName("listUsers filters out PATIENT accounts and returns only staff")
    void testListUsersExcludesPatients() {
        User doctor = new User();
        doctor.setId(UUID.randomUUID());
        doctor.setEmail("dr.smith@hospital.com");
        doctor.setRole(Role.DOCTOR);
        doctor.setCreatedAt(LocalDateTime.now());

        User auditor = new User();
        auditor.setId(UUID.randomUUID());
        auditor.setEmail("auditor@hospital.com");
        auditor.setRole(Role.AUDITOR);
        auditor.setCreatedAt(LocalDateTime.now());

        User admin = new User();
        admin.setId(UUID.randomUUID());
        admin.setEmail("admin@hospital.com");
        admin.setRole(Role.ADMIN);
        admin.setCreatedAt(LocalDateTime.now());

        User patient = new User();
        patient.setId(UUID.randomUUID());
        patient.setEmail("patient@example.com");
        patient.setRole(Role.PATIENT);
        patient.setCreatedAt(LocalDateTime.now());

        when(userRepository.findAll()).thenReturn(List.of(doctor, auditor, admin, patient));

        ResponseEntity<List<AdminUserResponse>> response = adminController.listUsers();
        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertNotNull(response.getBody());
        assertEquals(3, response.getBody().size());

        List<Role> returnedRoles = response.getBody().stream().map(AdminUserResponse::getRole).toList();
        assertTrue(returnedRoles.contains(Role.DOCTOR));
        assertTrue(returnedRoles.contains(Role.AUDITOR));
        assertTrue(returnedRoles.contains(Role.ADMIN));
        assertFalse(returnedRoles.contains(Role.PATIENT));
    }

    @Test
    @DisplayName("createUser auto-generates temporary password when null or blank")
    void testCreateUserWithAutoGeneratedPassword() {
        AdminUserRequest request = new AdminUserRequest();
        request.setEmail("new.doctor@hospital.com");
        request.setRole(Role.DOCTOR);
        request.setPassword(null);

        when(userRepository.existsByEmail("new.doctor@hospital.com")).thenReturn(false);
        when(userRepository.save(any(User.class))).thenAnswer(invocation -> {
            User u = invocation.getArgument(0);
            u.setId(UUID.randomUUID());
            u.setCreatedAt(LocalDateTime.now());
            return u;
        });

        ResponseEntity<AdminUserResponse> response = adminController.createUser(request);
        assertEquals(HttpStatus.CREATED, response.getStatusCode());
        assertNotNull(response.getBody());
        assertEquals("new.doctor@hospital.com", response.getBody().getEmail());
        assertEquals(Role.DOCTOR, response.getBody().getRole());
        assertNotNull(response.getBody().getTemporaryPassword(), "Temporary password should be generated");
        assertFalse(response.getBody().getTemporaryPassword().isBlank());
        assertNotNull(response.getBody().getCreatedAt());

        verify(passwordEncoder).encode(response.getBody().getTemporaryPassword());
        verify(userRepository).save(any(User.class));
    }

    @Test
    @DisplayName("createUser uses explicit password when provided")
    void testCreateUserWithExplicitPassword() {
        String explicitPassword = "test-mock-explicit-password-" + UUID.randomUUID();
        AdminUserRequest request = new AdminUserRequest();
        request.setEmail("custom.auditor@hospital.com");
        request.setRole(Role.AUDITOR);
        request.setPassword(explicitPassword);

        when(userRepository.existsByEmail("custom.auditor@hospital.com")).thenReturn(false);
        when(userRepository.save(any(User.class))).thenAnswer(invocation -> {
            User u = invocation.getArgument(0);
            u.setId(UUID.randomUUID());
            u.setCreatedAt(LocalDateTime.now());
            return u;
        });

        ResponseEntity<AdminUserResponse> response = adminController.createUser(request);
        assertEquals(HttpStatus.CREATED, response.getStatusCode());
        assertNotNull(response.getBody());
        assertEquals("custom.auditor@hospital.com", response.getBody().getEmail());
        assertEquals(Role.AUDITOR, response.getBody().getRole());
        assertNull(response.getBody().getTemporaryPassword(), "No temporary password should be returned when custom password was set");

        verify(passwordEncoder).encode(explicitPassword);
        verify(userRepository).save(any(User.class));
    }

    @Test
    @DisplayName("createUser throws exception when email is already registered")
    void testCreateUserDuplicateEmail() {
        AdminUserRequest request = new AdminUserRequest();
        request.setEmail("existing@hospital.com");
        request.setRole(Role.DOCTOR);

        when(userRepository.existsByEmail("existing@hospital.com")).thenReturn(true);

        assertThrows(IllegalArgumentException.class, () -> adminController.createUser(request));
        verify(userRepository, never()).save(any(User.class));
    }

    @Test
    @DisplayName("updateUser successfully updates staff role and email")
    void testUpdateUserSuccess() {
        UUID userId = UUID.randomUUID();
        User existing = new User();
        existing.setId(userId);
        existing.setEmail("doctor@hospital.com");
        existing.setRole(Role.DOCTOR);
        existing.setCreatedAt(LocalDateTime.now());

        when(userRepository.findById(userId)).thenReturn(Optional.of(existing));
        when(userRepository.save(any(User.class))).thenAnswer(invocation -> invocation.getArgument(0));

        AdminUserRequest updateReq = new AdminUserRequest();
        updateReq.setEmail("doctor.promoted@hospital.com");
        updateReq.setRole(Role.ADMIN);

        ResponseEntity<AdminUserResponse> response = adminController.updateUser(userId, updateReq);
        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertNotNull(response.getBody());
        assertEquals("doctor.promoted@hospital.com", response.getBody().getEmail());
        assertEquals(Role.ADMIN, response.getBody().getRole());
        assertNull(response.getBody().getTemporaryPassword());
        verify(userRepository).save(existing);
    }

    @Test
    @DisplayName("updateUser with AUTO_GENERATE password generates new temporary password")
    void testUpdateUserWithAutoGeneratedPassword() {
        UUID userId = UUID.randomUUID();
        User existing = new User();
        existing.setId(userId);
        existing.setEmail("auditor@hospital.com");
        existing.setRole(Role.AUDITOR);
        existing.setCreatedAt(LocalDateTime.now());

        when(userRepository.findById(userId)).thenReturn(Optional.of(existing));
        when(userRepository.save(any(User.class))).thenAnswer(invocation -> invocation.getArgument(0));

        AdminUserRequest updateReq = new AdminUserRequest();
        updateReq.setEmail("auditor@hospital.com");
        updateReq.setRole(Role.AUDITOR);
        updateReq.setPassword("AUTO_GENERATE");

        ResponseEntity<AdminUserResponse> response = adminController.updateUser(userId, updateReq);
        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertNotNull(response.getBody());
        assertNotNull(response.getBody().getTemporaryPassword());
        assertFalse(response.getBody().getTemporaryPassword().isBlank());
        verify(passwordEncoder).encode(response.getBody().getTemporaryPassword());
        verify(userRepository).save(existing);
    }

    @Test
    @DisplayName("deleteUser successfully deletes existing user")
    void testDeleteUserSuccess() {
        UUID userId = UUID.randomUUID();
        User user = new User();
        user.setId(userId);
        user.setEmail("staff@hospital.com");

        when(userRepository.findById(userId)).thenReturn(Optional.of(user));

        ResponseEntity<Void> response = adminController.deleteUser(userId);
        assertEquals(HttpStatus.NO_CONTENT, response.getStatusCode());
        verify(userRepository).delete(user);
    }

    @Test
    @DisplayName("deleteUser throws exception when user does not exist")
    void testDeleteUserNotFound() {
        UUID userId = UUID.randomUUID();
        when(userRepository.findById(userId)).thenReturn(Optional.empty());

        assertThrows(IllegalArgumentException.class, () -> adminController.deleteUser(userId));
        verify(userRepository, never()).delete(any(User.class));
    }
}
